logging:
  level:
    org.springframework.security: DEBUG
security:
    ignored: /css/**,/js/**,/favicon.ico,/webjars/**
    user:
      name: user
      password: password
server:
    contextPath: /uaa
spring:
  thymeleaf:
    mode: LEGACYHTML5