spring:
  application:
    name: register-server
server:
  port: 7777
security:
  user:
    name: admin
    password: passwd
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://admin:passwd@127.0.0.1:7777/eureka
    fetch-registry: false
    register-with-eureka: false
