
package io.github.daviszhao.stonemason.db.event.tables.daos;


import io.github.daviszhao.stonemason.db.base.daos.AbstractDao;
import io.github.daviszhao.stonemason.db.event.tables.EventWatchTable;
import io.github.daviszhao.stonemason.db.event.tables.records.EventWatchRecord;
import io.github.daviszhao.stonemason.models.event.EventWatch;
import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.time.LocalDateTime;
import java.util.List;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Repository
public class EventWatchDao extends AbstractDao<EventWatchRecord, EventWatch, Integer> {

    /**
     * Create a new EventWatchDao without any configuration
     */
    public EventWatchDao() {
        super(EventWatchTable.eventWatch, EventWatch.class);
    }

    /**
     * Create a new EventWatchDao with an attached configuration
     */
    @Autowired
    public EventWatchDao(Configuration configuration) {
        super(EventWatchTable.eventWatch, EventWatch.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(EventWatch object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<EventWatch> fetchById(Integer... values) {
        return fetch(EventWatchTable.eventWatch.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public EventWatch fetchOneById(Integer value) {
        return fetchOne(EventWatchTable.eventWatch.ID, value);
    }

    /**
     * Fetch records that have <code>extraParams IN (values)</code>
     */
    public List<EventWatch> fetchByExtraparams(String... values) {
        return fetch(EventWatchTable.eventWatch.EXTRAPARAMS, values);
    }

    /**
     * Fetch records that have <code>askEventIds IN (values)</code>
     */
    public List<EventWatch> fetchByAskeventids(String... values) {
        return fetch(EventWatchTable.eventWatch.ASKEVENTIDS, values);
    }

    /**
     * Fetch records that have <code>callbackClass IN (values)</code>
     */
    public List<EventWatch> fetchByCallbackclass(String... values) {
        return fetch(EventWatchTable.eventWatch.CALLBACKCLASS, values);
    }

    /**
     * Fetch records that have <code>united IN (values)</code>
     */
    public List<EventWatch> fetchByUnited(Boolean... values) {
        return fetch(EventWatchTable.eventWatch.UNITED, values);
    }

    /**
     * Fetch records that have <code>askEventStatus IN (values)</code>
     */
    public List<EventWatch> fetchByAskeventstatus(String... values) {
        return fetch(EventWatchTable.eventWatch.ASKEVENTSTATUS, values);
    }

    /**
     * Fetch records that have <code>timeoutTime IN (values)</code>
     */
    public List<EventWatch> fetchByTimeouttime(LocalDateTime... values) {
        return fetch(EventWatchTable.eventWatch.TIMEOUTTIME, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<EventWatch> fetchByVersion(Integer... values) {
        return fetch(EventWatchTable.eventWatch.VERSION, values);
    }
}
