
package io.github.daviszhao.stonemason.db.event.tables.daos;


import io.github.daviszhao.stonemason.busEvent.constants.ProcessStatus;
import io.github.daviszhao.stonemason.db.base.daos.AbstractDao;
import io.github.daviszhao.stonemason.db.event.tables.RevokeAskEventPublishTable;
import io.github.daviszhao.stonemason.db.event.tables.records.RevokeAskEventPublishRecord;
import io.github.daviszhao.stonemason.models.event.RevokeAskEventPublish;
import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.util.List;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Repository
public class RevokeAskEventPublishDao extends AbstractDao<RevokeAskEventPublishRecord, RevokeAskEventPublish, Integer> {

    /**
     * Create a new RevokeAskEventPublishDao without any configuration
     */
    public RevokeAskEventPublishDao() {
        super(RevokeAskEventPublishTable.revokeAskEventPublish, RevokeAskEventPublish.class);
    }

    /**
     * Create a new RevokeAskEventPublishDao with an attached configuration
     */
    @Autowired
    public RevokeAskEventPublishDao(Configuration configuration) {
        super(RevokeAskEventPublishTable.revokeAskEventPublish, RevokeAskEventPublish.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(RevokeAskEventPublish object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<RevokeAskEventPublish> fetchById(Integer... values) {
        return fetch(RevokeAskEventPublishTable.revokeAskEventPublish.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public RevokeAskEventPublish fetchOneById(Integer value) {
        return fetchOne(RevokeAskEventPublishTable.revokeAskEventPublish.ID, value);
    }

    /**
     * Fetch records that have <code>payload IN (values)</code>
     */
    public List<RevokeAskEventPublish> fetchByPayload(String... values) {
        return fetch(RevokeAskEventPublishTable.revokeAskEventPublish.PAYLOAD, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<RevokeAskEventPublish> fetchByStatus(ProcessStatus... values) {
        return fetch(RevokeAskEventPublishTable.revokeAskEventPublish.STATUS, values);
    }

    /**
     * Fetch records that have <code>eventId IN (values)</code>
     */
    public List<RevokeAskEventPublish> fetchByEventid(String... values) {
        return fetch(RevokeAskEventPublishTable.revokeAskEventPublish.EVENTID, values);
    }

    /**
     * Fetch a unique record that has <code>eventId = value</code>
     */
    public RevokeAskEventPublish fetchOneByEventid(String value) {
        return fetchOne(RevokeAskEventPublishTable.revokeAskEventPublish.EVENTID, value);
    }

    /**
     * Fetch records that have <code>askEventId IN (values)</code>
     */
    public List<RevokeAskEventPublish> fetchByAskeventid(String... values) {
        return fetch(RevokeAskEventPublishTable.revokeAskEventPublish.ASKEVENTID, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<RevokeAskEventPublish> fetchByVersion(Integer... values) {
        return fetch(RevokeAskEventPublishTable.revokeAskEventPublish.VERSION, values);
    }

    /**
     * Fetch records that have <code>eventType IN (values)</code>
     */
    public List<RevokeAskEventPublish> fetchByEventtype(String... values) {
        return fetch(RevokeAskEventPublishTable.revokeAskEventPublish.EVENTTYPE, values);
    }
}
