/*
 * This file is generated by jOOQ.
 */
package io.github.daviszhao.stonemason.db.user;


import org.jooq.impl.CatalogImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DefaultCatalog extends CatalogImpl {

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();
    private static final long serialVersionUID = -207084955;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }
}
