/*
 * This file is generated by jOOQ.
 */
package io.github.daviszhao.stonemason.db.user;


import org.jooq.Catalog;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class User extends SchemaImpl {

    /**
     * The reference instance of <code>user</code>
     */
    public static final User USER = new User();
    private static final long serialVersionUID = 528885951;

    /**
     * No further instances allowed
     */
    private User() {
        super("user", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }
}
