/*
 * This file is generated by jOOQ.
 */
package io.github.daviszhao.stonemason.db.event.tables.records;


import io.github.daviszhao.stonemason.busEvent.constants.AskEventStatus;
import io.github.daviszhao.stonemason.busEvent.constants.ProcessStatus;
import io.github.daviszhao.stonemason.db.event.tables.AskRequstEventPublishTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AskRequstEventPublishRecord extends UpdatableRecordImpl<AskRequstEventPublishRecord> implements Record10<Integer, String, ProcessStatus, String, AskEventStatus, Integer, String, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -2093197256;
    private final static AskRequstEventPublishTable TABLE = AskRequstEventPublishTable.askRequstEventPublish;

    /**
     * Create a detached AskRequstEventPublishRecord
     */
    public AskRequstEventPublishRecord() {
        super(TABLE);
    }

    /**
     * Create a detached, initialised AskRequstEventPublishRecord
     */
    public AskRequstEventPublishRecord(Integer id, String payload, ProcessStatus status, String eventid, AskEventStatus askeventstatus, Integer watchid, String eventtype, Integer version, LocalDateTime createtime, LocalDateTime updatetime) {
        super(TABLE);

        set(0, id);
        set(1, payload);
        set(2, status);
        set(3, eventid);
        set(4, askeventstatus);
        set(5, watchid);
        set(6, eventtype);
        set(7, version);
        set(8, createtime);
        set(9, updatetime);
    }

    /**
     * Getter for <code>user.t_ask_requst_event_publish.id</code>.
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>user.t_ask_requst_event_publish.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>user.t_ask_requst_event_publish.payload</code>.
     */
    public String getPayload() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user.t_ask_requst_event_publish.payload</code>.
     */
    public void setPayload(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user.t_ask_requst_event_publish.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    @Size(max = 20)
    public ProcessStatus getStatus() {
        return (ProcessStatus) get(2);
    }

    /**
     * Setter for <code>user.t_ask_requst_event_publish.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    public void setStatus(ProcessStatus value) {
        set(2, value);
    }

    /**
     * Getter for <code>user.t_ask_requst_event_publish.eventId</code>.
     */
    @Size(max = 50)
    public String getEventid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user.t_ask_requst_event_publish.eventId</code>.
     */
    public void setEventid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>user.t_ask_requst_event_publish.askEventStatus</code>. 'PENDING','TIMEOUT','FAILED','SUCCESS','CANCELLED'
     */
    @Size(max = 20)
    public AskEventStatus getAskeventstatus() {
        return (AskEventStatus) get(4);
    }

    /**
     * Setter for <code>user.t_ask_requst_event_publish.askEventStatus</code>. 'PENDING','TIMEOUT','FAILED','SUCCESS','CANCELLED'
     */
    public void setAskeventstatus(AskEventStatus value) {
        set(4, value);
    }

    /**
     * Getter for <code>user.t_ask_requst_event_publish.watchId</code>.
     */
    public Integer getWatchid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>user.t_ask_requst_event_publish.watchId</code>.
     */
    public void setWatchid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>user.t_ask_requst_event_publish.eventType</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getEventtype() {
        return (String) get(6);
    }

    /**
     * Setter for <code>user.t_ask_requst_event_publish.eventType</code>.
     */
    public void setEventtype(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>user.t_ask_requst_event_publish.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>user.t_ask_requst_event_publish.version</code>.
     */
    public void setVersion(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>user.t_ask_requst_event_publish.createTime</code>.
     */
    public LocalDateTime getCreatetime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>user.t_ask_requst_event_publish.createTime</code>.
     */
    public void setCreatetime(LocalDateTime value) {
        set(8, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>user.t_ask_requst_event_publish.updateTime</code>.
     */
    public LocalDateTime getUpdatetime() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 eventType implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>user.t_ask_requst_event_publish.updateTime</code>.
     */
    public void setUpdatetime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, ProcessStatus, String, AskEventStatus, Integer, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, ProcessStatus, String, AskEventStatus, Integer, String, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TABLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TABLE.PAYLOAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ProcessStatus> field3() {
        return TABLE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TABLE.EVENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<AskEventStatus> field5() {
        return TABLE.ASKEVENTSTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TABLE.WATCHID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TABLE.EVENTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TABLE.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return TABLE.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return TABLE.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPayload();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessStatus value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEventid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskEventStatus value5() {
        return getAskeventstatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getWatchid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEventtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskRequstEventPublishRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskRequstEventPublishRecord value2(String value) {
        setPayload(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskRequstEventPublishRecord value3(ProcessStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskRequstEventPublishRecord value4(String value) {
        setEventid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     *
     * @param value
     */
    @Override
    public AskRequstEventPublishRecord value5(AskEventStatus value) {
        setAskeventstatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskRequstEventPublishRecord value6(Integer value) {
        setWatchid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskRequstEventPublishRecord value7(String value) {
        setEventtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskRequstEventPublishRecord value8(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskRequstEventPublishRecord value9(LocalDateTime value) {
        setCreatetime(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public AskRequstEventPublishRecord value10(LocalDateTime value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskRequstEventPublishRecord values(Integer value1, String value2, ProcessStatus value3, String value4, AskEventStatus value5, Integer value6, String value7, Integer value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }
}
