/*
 * This file is generated by jOOQ.
 */
package io.github.daviszhao.stonemason.db.event.tables.records;


import io.github.daviszhao.stonemason.busEvent.constants.ProcessStatus;
import io.github.daviszhao.stonemason.busEvent.payloads.EventPayload;
import io.github.daviszhao.stonemason.db.event.tables.AskResponseEventPublishTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AskResponseEventPublishRecord extends UpdatableRecordImpl<AskResponseEventPublishRecord> implements Record10<Integer, EventPayload, ProcessStatus, String, Boolean, String, String, Integer, LocalDateTime, LocalDateTime> {

    public static final AskResponseEventPublishTable TABLE = AskResponseEventPublishTable.ASK_RESPONSE_EVENT_PUBLISH;
    private static final long serialVersionUID = -669040813;

    /**
     * Create a detached AskResponseEventPublishRecord
     */
    public AskResponseEventPublishRecord() {
        super(TABLE);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.id</code>.
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Create a detached, initialised AskResponseEventPublishRecord
     */
    public AskResponseEventPublishRecord(Integer id, String payload, String status, String eventid, Boolean success, String askeventid, String eventtype, Integer version, LocalDateTime createtime, LocalDateTime updatetime) {
        super(TABLE);

        set(0, id);
        set(1, payload);
        set(2, status);
        set(3, eventid);
        set(4, success);
        set(5, askeventid);
        set(6, eventtype);
        set(7, version);
        set(8, createtime);
        set(9, updatetime);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.payload</code>.
     */
    @Size(max = 65535)
    public EventPayload getPayload() {
        return (EventPayload) get(1);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    @Size(max = 20)
    public ProcessStatus getStatus() {
        return (ProcessStatus) get(2);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.payload</code>.
     */
    public void setPayload(EventPayload value) {
        set(1, value);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.eventId</code>.
     */
    @Size(max = 50)
    public String getEventid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    public void setStatus(ProcessStatus value) {
        set(2, value);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.success</code>.
     */
    public Boolean getSuccess() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.eventId</code>.
     */
    public void setEventid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.askEventId</code>.
     */
    @Size(max = 50)
    public String getAskeventid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.success</code>.
     */
    public void setSuccess(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.eventType</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getEventtype() {
        return (String) get(6);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.askEventId</code>.
     */
    public void setAskeventid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.eventType</code>.
     */
    public void setEventtype(String value) {
        set(6, value);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.version</code>.
     */
    public void setVersion(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.createTime</code>.
     */
    public LocalDateTime getCreatetime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.createTime</code>.
     */
    public void setCreatetime(LocalDateTime value) {
        set(8, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>user.t_ask_response_event_publish.updateTime</code>.
     */
    public LocalDateTime getUpdatetime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.updateTime</code>.
     */
    public void setUpdatetime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, EventPayload, ProcessStatus, String, Boolean, String, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, EventPayload, ProcessStatus, String, Boolean, String, String, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TABLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EventPayload> field2() {
        return TABLE.PAYLOAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ProcessStatus> field3() {
        return TABLE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TABLE.EVENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return TABLE.SUCCESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TABLE.ASKEVENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TABLE.EVENTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TABLE.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return TABLE.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessStatus value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEventid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getSuccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAskeventid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEventtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return TABLE.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventPayload value2() {
        return getPayload();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value2(EventPayload value) {
        setPayload(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value3(ProcessStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value4(String value) {
        setEventid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value5(Boolean value) {
        setSuccess(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value6(String value) {
        setAskeventid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value7(String value) {
        setEventtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value8(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value9(LocalDateTime value) {
        setCreatetime(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value10(LocalDateTime value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord values(Integer value1, EventPayload value2, ProcessStatus value3, String value4, Boolean value5, String value6, String value7, Integer value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }
}
