/*
 * This file is generated by jOOQ.
 */
package io.github.daviszhao.stonemason.db.event.tables.records;


import io.github.daviszhao.stonemason.db.event.tables.AskResponseEventPublishTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AskResponseEventPublishRecord extends UpdatableRecordImpl<AskResponseEventPublishRecord> implements Record8<Integer, String, String, String, Boolean, String, String, Integer> {

    private static final long serialVersionUID = -129838234;

    /**
     * Create a detached AskResponseEventPublishRecord
     */
    public AskResponseEventPublishRecord() {
        super(AskResponseEventPublishTable.askResponseEventPublish);
    }

    /**
     * Create a detached, initialised AskResponseEventPublishRecord
     */
    public AskResponseEventPublishRecord(Integer id, String payload, String status, String eventid, Boolean success, String askeventid, String eventtype, Integer version) {
        super(AskResponseEventPublishTable.askResponseEventPublish);

        set(0, id);
        set(1, payload);
        set(2, status);
        set(3, eventid);
        set(4, success);
        set(5, askeventid);
        set(6, eventtype);
        set(7, version);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.id</code>.
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.payload</code>.
     */
    @Size(max = 65535)
    public String getPayload() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.payload</code>.
     */
    public void setPayload(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    @Size(max = 20)
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.eventId</code>.
     */
    @Size(max = 50)
    public String getEventid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.eventId</code>.
     */
    public void setEventid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.success</code>.
     */
    public Boolean getSuccess() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.success</code>.
     */
    public void setSuccess(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.askEventId</code>.
     */
    @Size(max = 50)
    public String getAskeventid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.askEventId</code>.
     */
    public void setAskeventid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>user.t_ask_response_event_publish.eventType</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getEventtype() {
        return (String) get(6);
    }

    /**
     * Setter for <code>user.t_ask_response_event_publish.eventType</code>.
     */
    public void setEventtype(String value) {
        set(6, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>user.t_ask_response_event_publish.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>user.t_ask_response_event_publish.version</code>.
     */
    public void setVersion(Integer value) {
        set(7, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Boolean, String, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Boolean, String, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AskResponseEventPublishTable.askResponseEventPublish.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AskResponseEventPublishTable.askResponseEventPublish.PAYLOAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AskResponseEventPublishTable.askResponseEventPublish.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AskResponseEventPublishTable.askResponseEventPublish.EVENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return AskResponseEventPublishTable.askResponseEventPublish.SUCCESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return AskResponseEventPublishTable.askResponseEventPublish.ASKEVENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return AskResponseEventPublishTable.askResponseEventPublish.EVENTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return AskResponseEventPublishTable.askResponseEventPublish.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPayload();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEventid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getSuccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAskeventid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEventtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value2(String value) {
        setPayload(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value3(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value4(String value) {
        setEventid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value5(Boolean value) {
        setSuccess(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value6(String value) {
        setAskeventid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value7(String value) {
        setEventtype(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord value8(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AskResponseEventPublishRecord values(Integer value1, String value2, String value3, String value4, Boolean value5, String value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }
}
