/*
 * This file is generated by jOOQ.
 */
package io.github.daviszhao.stonemason.db.event.tables.records;


import io.github.daviszhao.stonemason.db.event.tables.EventProcessTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EventProcessRecord extends UpdatableRecordImpl<EventProcessRecord> implements Record7<Integer, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = 1416979066;

    /**
     * Create a detached EventProcessRecord
     */
    public EventProcessRecord() {
        super(EventProcessTable.eventProcess);
    }

    /**
     * Create a detached, initialised EventProcessRecord
     */
    public EventProcessRecord(Integer id, String payload, String status, String eventcategory, String eventid, String eventtype, Integer version) {
        super(EventProcessTable.eventProcess);

        set(0, id);
        set(1, payload);
        set(2, status);
        set(3, eventcategory);
        set(4, eventid);
        set(5, eventtype);
        set(6, version);
    }

    /**
     * Getter for <code>user.t_event_process.id</code>.
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>user.t_event_process.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>user.t_event_process.payload</code>. 携带的数据
     */
    @Size(max = 65535)
    public String getPayload() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user.t_event_process.payload</code>. 携带的数据
     */
    public void setPayload(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user.t_event_process.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    @Size(max = 20)
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user.t_event_process.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user.t_event_process.eventCategory</code>. 'NOTIFY','ASK','REVOKE','ASKRESP'
     */
    @NotNull
    @Size(max = 20)
    public String getEventcategory() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user.t_event_process.eventCategory</code>. 'NOTIFY','ASK','REVOKE','ASKRESP'
     */
    public void setEventcategory(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>user.t_event_process.eventId</code>.
     */
    @Size(max = 50)
    public String getEventid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>user.t_event_process.eventId</code>.
     */
    public void setEventid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>user.t_event_process.eventType</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getEventtype() {
        return (String) get(5);
    }

    /**
     * Setter for <code>user.t_event_process.eventType</code>.
     */
    public void setEventtype(String value) {
        set(5, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>user.t_event_process.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>user.t_event_process.version</code>.
     */
    public void setVersion(Integer value) {
        set(6, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, String, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EventProcessTable.eventProcess.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EventProcessTable.eventProcess.PAYLOAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return EventProcessTable.eventProcess.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return EventProcessTable.eventProcess.EVENTCATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return EventProcessTable.eventProcess.EVENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return EventProcessTable.eventProcess.EVENTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return EventProcessTable.eventProcess.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPayload();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEventcategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEventid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEventtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value2(String value) {
        setPayload(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value3(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value4(String value) {
        setEventcategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value5(String value) {
        setEventid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value6(String value) {
        setEventtype(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value7(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }
}
