/*
 * This file is generated by jOOQ.
 */
package io.github.daviszhao.stonemason.db.event.tables.records;


import io.github.daviszhao.stonemason.db.event.tables.EventWatchProcessTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EventWatchProcessRecord extends UpdatableRecordImpl<EventWatchProcessRecord> implements Record5<Integer, Integer, String, String, Integer> {

    private static final long serialVersionUID = 1177415787;

    /**
     * Create a detached EventWatchProcessRecord
     */
    public EventWatchProcessRecord() {
        super(EventWatchProcessTable.eventWatchProcess);
    }

    /**
     * Create a detached, initialised EventWatchProcessRecord
     */
    public EventWatchProcessRecord(Integer id, Integer watchid, String status, String failureinfo, Integer version) {
        super(EventWatchProcessTable.eventWatchProcess);

        set(0, id);
        set(1, watchid);
        set(2, status);
        set(3, failureinfo);
        set(4, version);
    }

    /**
     * Getter for <code>user.t_event_watch_process.id</code>.
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>user.t_event_watch_process.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>user.t_event_watch_process.watchId</code>.
     */
    @NotNull
    public Integer getWatchid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>user.t_event_watch_process.watchId</code>.
     */
    public void setWatchid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>user.t_event_watch_process.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    @NotNull
    @Size(max = 20)
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user.t_event_watch_process.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user.t_event_watch_process.failureInfo</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getFailureinfo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user.t_event_watch_process.failureInfo</code>.
     */
    public void setFailureinfo(String value) {
        set(3, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>user.t_event_watch_process.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>user.t_event_watch_process.version</code>.
     */
    public void setVersion(Integer value) {
        set(4, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EventWatchProcessTable.eventWatchProcess.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return EventWatchProcessTable.eventWatchProcess.WATCHID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return EventWatchProcessTable.eventWatchProcess.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return EventWatchProcessTable.eventWatchProcess.FAILUREINFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return EventWatchProcessTable.eventWatchProcess.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getWatchid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFailureinfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventWatchProcessRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventWatchProcessRecord value2(Integer value) {
        setWatchid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventWatchProcessRecord value3(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventWatchProcessRecord value4(String value) {
        setFailureinfo(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public EventWatchProcessRecord value5(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventWatchProcessRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
