/*
 * This file is generated by jOOQ.
 */
package io.github.daviszhao.stonemason.db.event.tables.records;


import io.github.daviszhao.stonemason.busEvent.constants.EventCategory;
import io.github.daviszhao.stonemason.busEvent.constants.ProcessStatus;
import io.github.daviszhao.stonemason.db.event.tables.EventProcessTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;

@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EventProcessRecord extends UpdatableRecordImpl<EventProcessRecord> implements Record9<Integer, String, ProcessStatus, EventCategory, String, String, Integer, LocalDateTime, LocalDateTime> {

    public static final EventProcessTable TABLE = EventProcessTable.EVENT_PROCESS;
    private static final long serialVersionUID = 311055922;

    /**
     * Create a detached EventProcessRecord
     */
    public EventProcessRecord() {
        super(TABLE);
    }

    /**
     * Getter for <code>user.t_event_process.id</code>.
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Create a detached, initialised EventProcessRecord
     */
    public EventProcessRecord(Integer id, String payload, ProcessStatus status, EventCategory eventcategory, String eventid, String eventtype, Integer version, LocalDateTime createtime, LocalDateTime updatetime) {
        super(TABLE);

        set(0, id);
        set(1, payload);
        set(2, status);
        set(3, eventcategory);
        set(4, eventid);
        set(5, eventtype);
        set(6, version);
        set(7, createtime);
        set(8, updatetime);
    }

    /**
     * Getter for <code>user.t_event_process.payload</code>. 携带的数据
     */
    @Size(max = 65535)
    public String getPayload() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user.t_event_process.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Setter for <code>user.t_event_process.payload</code>. 携带的数据
     */
    public void setPayload(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user.t_event_process.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    @Size(max = 20)
    public ProcessStatus getStatus() {
        return (ProcessStatus) get(2);
    }

    /**
     * Setter for <code>user.t_event_process.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    public void setStatus(ProcessStatus value) {
        set(2, value);
    }

    /**
     * Getter for <code>user.t_event_process.eventCategory</code>. 'NOTIFY','ASK','REVOKE','ASKRESP'
     */
    @NotNull
    @Size(max = 20)
    public EventCategory getEventcategory() {
        return (EventCategory) get(3);
    }

    /**
     * Getter for <code>user.t_event_process.eventId</code>.
     */
    @Size(max = 50)
    public String getEventid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>user.t_event_process.eventCategory</code>. 'NOTIFY','ASK','REVOKE','ASKRESP'
     */
    public void setEventcategory(EventCategory value) {
        set(3, value);
    }

    /**
     * Getter for <code>user.t_event_process.eventType</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getEventtype() {
        return (String) get(5);
    }

    /**
     * Setter for <code>user.t_event_process.eventId</code>.
     */
    public void setEventid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>user.t_event_process.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>user.t_event_process.eventType</code>.
     */
    public void setEventtype(String value) {
        set(5, value);
    }

    /**
     * Setter for <code>user.t_event_process.version</code>.
     */
    public void setVersion(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>user.t_event_process.createTime</code>.
     */
    public LocalDateTime getCreatetime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>user.t_event_process.createTime</code>.
     */
    public void setCreatetime(LocalDateTime value) {
        set(7, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>user.t_event_process.updateTime</code>.
     */
    public LocalDateTime getUpdatetime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>user.t_event_process.updateTime</code>.
     */
    public void setUpdatetime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, ProcessStatus, EventCategory, String, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, ProcessStatus, EventCategory, String, String, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TABLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TABLE.PAYLOAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ProcessStatus> field3() {
        return TABLE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EventCategory> field4() {
        return TABLE.EVENTCATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TABLE.EVENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TABLE.EVENTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TABLE.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPayload();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return TABLE.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return TABLE.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEventid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEventtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessStatus value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventCategory value4() {
        return getEventcategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value2(String value) {
        setPayload(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value5(String value) {
        setEventid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value6(String value) {
        setEventtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value7(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value3(ProcessStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value4(EventCategory value) {
        setEventcategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value8(LocalDateTime value) {
        setCreatetime(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord value9(LocalDateTime value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventProcessRecord values(Integer value1, String value2, ProcessStatus value3, EventCategory value4, String value5, String value6, Integer value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }
}
