/*
 * This file is generated by jOOQ.
 */
package io.github.daviszhao.stonemason.db.event.tables.records;


import io.github.daviszhao.stonemason.busEvent.constants.ProcessStatus;
import io.github.daviszhao.stonemason.busEvent.payloads.FailureInfo;
import io.github.daviszhao.stonemason.db.event.tables.EventWatchProcessTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EventWatchProcessRecord extends UpdatableRecordImpl<EventWatchProcessRecord> implements Record7<Integer, Integer, ProcessStatus, FailureInfo, Integer, LocalDateTime, LocalDateTime> {

    public static final EventWatchProcessTable TABLE = EventWatchProcessTable.EVENT_WATCH_PROCESS;
    private static final long serialVersionUID = 330395594;

    /**
     * Create a detached EventWatchProcessRecord
     */
    public EventWatchProcessRecord() {
        super(TABLE);
    }

    /**
     * Getter for <code>user.t_event_watch_process.id</code>.
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Create a detached, initialised EventWatchProcessRecord
     */
    public EventWatchProcessRecord(Integer id, Integer watchid, ProcessStatus status, FailureInfo failureinfo, Integer version, LocalDateTime createtime, LocalDateTime updatetime) {
        super(TABLE);

        set(0, id);
        set(1, watchid);
        set(2, status);
        set(3, failureinfo);
        set(4, version);
        set(5, createtime);
        set(6, updatetime);
    }

    /**
     * Getter for <code>user.t_event_watch_process.watchId</code>.
     */
    @NotNull
    public Integer getWatchid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>user.t_event_watch_process.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Setter for <code>user.t_event_watch_process.watchId</code>.
     */
    public void setWatchid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>user.t_event_watch_process.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    @NotNull
    @Size(max = 20)
    public ProcessStatus getStatus() {
        return (ProcessStatus) get(2);
    }

    /**
     * Setter for <code>user.t_event_watch_process.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    public void setStatus(ProcessStatus value) {
        set(2, value);
    }

    /**
     * Getter for <code>user.t_event_watch_process.failureInfo</code>.
     */
    @NotNull
    @Size(max = 255)
    public FailureInfo getFailureinfo() {
        return (FailureInfo) get(3);
    }

    /**
     * Getter for <code>user.t_event_watch_process.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>user.t_event_watch_process.failureInfo</code>.
     */
    public void setFailureinfo(FailureInfo value) {
        set(3, value);
    }

    /**
     * Setter for <code>user.t_event_watch_process.version</code>.
     */
    public void setVersion(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>user.t_event_watch_process.createTime</code>.
     */
    public LocalDateTime getCreatetime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>user.t_event_watch_process.createTime</code>.
     */
    public void setCreatetime(LocalDateTime value) {
        set(5, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 eventType implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>user.t_event_watch_process.updateTime</code>.
     */
    public LocalDateTime getUpdatetime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>user.t_event_watch_process.updateTime</code>.
     */
    public void setUpdatetime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, ProcessStatus, FailureInfo, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, ProcessStatus, FailureInfo, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TABLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TABLE.WATCHID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ProcessStatus> field3() {
        return TABLE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<FailureInfo> field4() {
        return TABLE.FAILUREINFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TABLE.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getWatchid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return TABLE.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return TABLE.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessStatus value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FailureInfo value4() {
        return getFailureinfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventWatchProcessRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventWatchProcessRecord value2(Integer value) {
        setWatchid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventWatchProcessRecord value5(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventWatchProcessRecord value3(ProcessStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventWatchProcessRecord value4(FailureInfo value) {
        setFailureinfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventWatchProcessRecord value6(LocalDateTime value) {
        setCreatetime(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public EventWatchProcessRecord value7(LocalDateTime value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventWatchProcessRecord values(Integer value1, Integer value2, ProcessStatus value3, FailureInfo value4, Integer value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }
}
