/*
 * This file is generated by jOOQ.
 */
package io.github.daviszhao.stonemason.db.event.tables.records;


import io.github.daviszhao.stonemason.db.event.tables.RevokeAskEventPublishTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RevokeAskEventPublishRecord extends UpdatableRecordImpl<RevokeAskEventPublishRecord> implements Record7<Integer, String, String, String, String, Integer, String> {

    private static final long serialVersionUID = 2121216900;

    /**
     * Create a detached RevokeAskEventPublishRecord
     */
    public RevokeAskEventPublishRecord() {
        super(RevokeAskEventPublishTable.revokeAskEventPublish);
    }

    /**
     * Create a detached, initialised RevokeAskEventPublishRecord
     */
    public RevokeAskEventPublishRecord(Integer id, String payload, String status, String eventid, String askeventid, Integer version, String eventtype) {
        super(RevokeAskEventPublishTable.revokeAskEventPublish);

        set(0, id);
        set(1, payload);
        set(2, status);
        set(3, eventid);
        set(4, askeventid);
        set(5, version);
        set(6, eventtype);
    }

    /**
     * Getter for <code>user.t_revoke_ask_event_publish.id</code>.
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>user.t_revoke_ask_event_publish.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>user.t_revoke_ask_event_publish.payload</code>.
     */
    @Size(max = 65535)
    public String getPayload() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user.t_revoke_ask_event_publish.payload</code>.
     */
    public void setPayload(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user.t_revoke_ask_event_publish.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    @Size(max = 20)
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user.t_revoke_ask_event_publish.status</code>. 'NEW','PROCESSED','IGNORE'
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user.t_revoke_ask_event_publish.eventId</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getEventid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user.t_revoke_ask_event_publish.eventId</code>.
     */
    public void setEventid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>user.t_revoke_ask_event_publish.askEventId</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getAskeventid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>user.t_revoke_ask_event_publish.askEventId</code>.
     */
    public void setAskeventid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>user.t_revoke_ask_event_publish.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>user.t_revoke_ask_event_publish.version</code>.
     */
    public void setVersion(Integer value) {
        set(5, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>user.t_revoke_ask_event_publish.eventType</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getEventtype() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>user.t_revoke_ask_event_publish.eventType</code>.
     */
    public void setEventtype(String value) {
        set(6, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RevokeAskEventPublishTable.revokeAskEventPublish.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RevokeAskEventPublishTable.revokeAskEventPublish.PAYLOAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return RevokeAskEventPublishTable.revokeAskEventPublish.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return RevokeAskEventPublishTable.revokeAskEventPublish.EVENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return RevokeAskEventPublishTable.revokeAskEventPublish.ASKEVENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return RevokeAskEventPublishTable.revokeAskEventPublish.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return RevokeAskEventPublishTable.revokeAskEventPublish.EVENTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPayload();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEventid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAskeventid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEventtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RevokeAskEventPublishRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RevokeAskEventPublishRecord value2(String value) {
        setPayload(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RevokeAskEventPublishRecord value3(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RevokeAskEventPublishRecord value4(String value) {
        setEventid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RevokeAskEventPublishRecord value5(String value) {
        setAskeventid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RevokeAskEventPublishRecord value6(Integer value) {
        setVersion(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RevokeAskEventPublishRecord value7(String value) {
        setEventtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RevokeAskEventPublishRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }
}
