package io.github.daviszhao.stonemason.models.event;


import io.github.daviszhao.stonemason.busEvent.constants.EventCategory;
import lombok.*;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@EqualsAndHashCode(callSuper = false)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AskRequstEventPublish extends AbstractEventPublish {

    private static final long serialVersionUID = -151363166;
    @Size(max = 20)
    private String askeventstatus;
    private Integer watchid;

    public AskRequstEventPublish(AskRequstEventPublish value) {
        this.setId(value.getId());
        this.setPayload(value.getPayload());
        this.setStatus(value.getStatus());
        this.setEventid(value.getEventid());
        this.askeventstatus = value.askeventstatus;
        this.watchid = value.watchid;
        this.setEventtype(value.getEventtype());
        setVersion(value.getVersion());
    }

    @Override
    public EventCategory getEventCategory() {
        return EventCategory.ASK;
    }
}
