
package io.github.daviszhao.stonemason.models.event;


import io.github.daviszhao.stonemason.busEvent.constants.EventCategory;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import javax.annotation.Generated;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Setter
@Getter
@NoArgsConstructor
@ToString
public class AskResponseEventPublish extends AbstractEventPublish {

    private static final long serialVersionUID = -1513668439;

    private Boolean success;
    private String askeventid;


    public AskResponseEventPublish(AskResponseEventPublish value) {
        this.setId(value.getId());
        this.setPayload(value.getPayload());
        this.setStatus(value.getStatus());
        this.setEventid(value.getEventid());
        this.success = value.success;
        this.askeventid = value.askeventid;
        this.setEventtype(value.getEventtype());
        this.setCreateTime(value.getCreateTime());
        this.setUpdateTime(value.getUpdateTime());
        this.setVersion(value.getVersion());
    }


    @Override
    public EventCategory getEventCategory() {
        return EventCategory.ASKRESP;
    }

}
