
package io.github.daviszhao.stonemason.models.event;


import io.github.daviszhao.stonemason.models.base.BaseModel;
import lombok.*;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@EqualsAndHashCode(callSuper = false)
public class EventWatchProcess extends BaseModel {

    private static final long serialVersionUID = -947228475;

    @NotNull
    private Integer id;
    @NotNull
    private Integer watchid;
    @NotNull
    @Size(max = 20)
    private String status;
    private String failureinfo;


    public EventWatchProcess(EventWatchProcess value) {
        this.id = value.id;
        this.watchid = value.watchid;
        this.status = value.status;
        this.failureinfo = value.failureinfo;
        setVersion(value.getVersion());
    }
}
