package io.github.daviszhao.stonemason.models.event;


import io.github.daviszhao.stonemason.busEvent.constants.EventCategory;
import io.github.daviszhao.stonemason.busEvent.constants.ProcessStatus;
import io.github.daviszhao.stonemason.busEvent.payloads.EventPayload;
import io.github.daviszhao.stonemason.models.base.BaseModel;
import lombok.*;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;

import static io.github.daviszhao.stonemason.busEvent.constants.ProcessStatus.NEW;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Setter
@Getter
@NoArgsConstructor
@ToString
@EqualsAndHashCode(callSuper = false)
public class EventProcess extends BaseModel {

    private static final long serialVersionUID = 2075324387;

    @NotNull
    private Integer id;
    @Size(max = 65535)
    private EventPayload payload;
    @Size(max = 20)
    private ProcessStatus status;
    @NotNull
    @Size(max = 20)
    private EventCategory eventcategory;
    @Size(max = 50)
    private String eventid;
    @NotNull
    @Size(max = 50)
    private String eventtype;
    private LocalDateTime createTime, updateTime;


    public EventProcess(EventProcess value) {
        this.id = value.id;
        this.payload = value.payload;
        this.status = value.status;
        this.eventcategory = value.eventcategory;
        this.eventid = value.eventid;
        this.eventtype = value.eventtype;
        this.setVersion(value.getVersion());
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;

    }

    public EventProcess(String type, EventCategory category, EventPayload payLoad, final String eventid) {
        this.id = null;
        this.payload = payload;
        this.status = NEW;
        this.eventcategory = category;
        this.eventid = eventid;
        this.eventtype = type;
        this.setVersion(0);
        this.createTime = LocalDateTime.now();
    }
}
