
package io.github.daviszhao.stonemason.models.event;


import io.github.daviszhao.stonemason.busEvent.constants.EventCategory;
import lombok.*;

import javax.annotation.Generated;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@EqualsAndHashCode(callSuper = false)
public class NotifyEventPublish extends AbstractEventPublish {

    private static final long serialVersionUID = 700733040;


    public NotifyEventPublish(NotifyEventPublish value) {
        this.setId(value.getId());
        this.setPayload(value.getPayload());
        this.setStatus(value.getStatus());
        this.setEventid(value.getEventid());
        this.setVersion(value.getVersion());
        this.setEventtype(value.getEventtype());
    }

    @Override
    public EventCategory getEventCategory() {
        return EventCategory.NOTIFY;
    }
}
