
package io.github.daviszhao.stonemason.models.event;


import io.github.daviszhao.stonemason.busEvent.constants.EventCategory;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Setter
@Getter
@NoArgsConstructor
@ToString
public class RevokeAskEventPublish extends AbstractEventPublish {

    private static final long serialVersionUID = -327625858;
    @NotNull
    @Size(max = 50)
    private String askeventid;

    public RevokeAskEventPublish(RevokeAskEventPublish value) {
        this.setId(value.getId());
        this.setPayload(value.getPayload());
        this.setStatus(value.getStatus());
        this.setEventid(value.getEventid());
        this.askeventid = value.askeventid;
        this.setVersion(value.getVersion());
        this.setEventtype(value.getEventtype());
        this.setCreateTime(value.getCreateTime());
        this.setUpdateTime(value.getUpdateTime());
    }

    @Override
    public EventCategory getEventCategory() {
        return EventCategory.REVOKE;
    }

}
